### ISSUE TITLE
Build error with protobuf-3.7.0

### ISSUE THREAD

**Issue by ghost** [squidfunk/protobluff#3]
Hi ,
I got this compile error when trying to build from source. May I know which protobuf version that you use to build this

make[3]: Entering directory '/home/tam/protobuf-analysis/protobluff/src/generator'
  CXX      protoc_gen_protobluff-enum.o
In file included from enum.cc:31:0:
../../src/generator/enum.hh:46:29: error: ‘google::protobuf::scoped_array’ has not been declared
   using ::google::protobuf::scoped_array;
                             ^~~~~~~~~~~~
../../src/generator/enum.hh:47:29: error: ‘google::protobuf::scoped_ptr’ has not been declared
   using ::google::protobuf::scoped_ptr;
                             ^~~~~~~~~~
../../src/generator/enum.hh:74:5: error: ‘scoped_array’ does not name a type; did you mean ‘sched_param’?
     scoped_array<
     ^~~~~~~~~~~~
     sched_param
In file included from enum.cc:33:0:
../../src/generator/strutil.hh:169:42: error: ‘vector’ has not been declared
                                          vector<string>* res);
                                          ^~~~~~
../../src/generator/strutil.hh:169:48: error: expected ‘,’ or ‘...’ before ‘<’ token
                                          vector<string>* res);
                                                ^
../../src/generator/strutil.hh:181:47: error: ‘vector’ has not been declared
                                               vector<string>* result);
                                               ^~~~~~
../../src/generator/strutil.hh:181:53: error: expected ‘,’ or ‘...’ before ‘<’ token
                                               vector<string>* result);
                                                     ^
../../src/generator/strutil.hh:191:43: error: ‘vector’ does not name a type; did you mean ‘perror’?
 LIBPROTOBUF_EXPORT void JoinStrings(const vector<string>& components,
                                           ^~~~~~
                                           perror
../../src/generator/strutil.hh:191:49: error: expected ‘,’ or ‘...’ before ‘<’ token
 LIBPROTOBUF_EXPORT void JoinStrings(const vector<string>& components,
                                                 ^
../../src/generator/strutil.hh:194:33: error: ‘vector’ does not name a type; did you mean ‘perror’?
 inline string JoinStrings(const vector<string>& components,
                                 ^~~~~~
                                 perror
../../src/generator/strutil.hh:194:39: error: expected ‘,’ or ‘...’ before ‘<’ token
 inline string JoinStrings(const vector<string>& components,
                                       ^
../../src/generator/strutil.hh: In function ‘std::__cxx11::string google::protobuf::JoinStrings(int)’:
../../src/generator/strutil.hh:194:15: error: ambiguating new declaration of ‘std::__cxx11::string google::protobuf::JoinStrings(int)’
 inline string JoinStrings(const vector<string>& components,
               ^~~~~~~~~~~
../../src/generator/strutil.hh:191:25: note: old declaration ‘void google::protobuf::JoinStrings(int)’
 LIBPROTOBUF_EXPORT void JoinStrings(const vector<string>& components,
                         ^~~~~~~~~~~
../../src/generator/strutil.hh:197:15: error: ‘components’ was not declared in this scope
   JoinStrings(components, delim, &result);
               ^~~~~~~~~~
../../src/generator/strutil.hh:197:27: error: ‘delim’ was not declared in this scope
   JoinStrings(components, delim, &result);
                           ^~~~~
../../src/generator/strutil.hh:197:27: note: suggested alternative: ‘getdelim’
   JoinStrings(components, delim, &result);
                           ^~~~~
                           getdelim
../../src/generator/strutil.hh: At global scope:
../../src/generator/strutil.hh:234:49: error: ‘vector’ has not been declared
                                                 vector<string> *errors);
                                                 ^~~~~~
../../src/generator/strutil.hh:234:55: error: expected ‘,’ or ‘...’ before ‘<’ token
                                                 vector<string> *errors);
                                                       ^
../../src/generator/strutil.hh:253:46: error: ‘vector’ has not been declared
                                              vector<string> *errors);
                                              ^~~~~~
../../src/generator/strutil.hh:253:52: error: expected ‘,’ or ‘...’ before ‘<’ token
                                              vector<string> *errors);
                                                    ^
enum.cc:47:29: error: ‘google::protobuf::scoped_ptr’ has not been declared
   using ::google::protobuf::scoped_ptr;
                             ^~~~~~~~~~
enum.cc: In constructor ‘protobluff::Enum::Enum(const google::protobuf::EnumDescriptor*)’:
enum.cc:61:7: error: class ‘protobluff::Enum’ does not have any field named ‘values_’
       values_(new scoped_ptr<EnumValue>[descriptor_->value_count()]) {
       ^~~~~~~
enum.cc:61:19: error: ‘scoped_ptr’ does not name a type; did you mean ‘sched_param’?
       values_(new scoped_ptr<EnumValue>[descriptor_->value_count()]) {
                   ^~~~~~~~~~
                   sched_param
enum.cc:61:39: error: expected primary-expression before ‘>’ token
       values_(new scoped_ptr<EnumValue>[descriptor_->value_count()]) {
                                       ^
enum.cc:61:41: error: capture of non-variable ‘protobluff::Enum::descriptor_’ 
       values_(new scoped_ptr<EnumValue>[descriptor_->value_count()]) {
                                         ^~~~~~~~~~~
In file included from enum.cc:31:0:
../../src/generator/enum.hh:73:27: note: ‘const google::protobuf::EnumDescriptor* protobluff::Enum::descriptor_’ declared here
     const EnumDescriptor *descriptor_; /* Enum descriptor */
                           ^~~~~~~~~~~
enum.cc:61:52: error: expected ‘,’ before ‘->’ token
       values_(new scoped_ptr<EnumValue>[descriptor_->value_count()]) {
                                                    ^~
enum.cc:61:52: error: expected identifier before ‘->’ token
enum.cc: In lambda function:
enum.cc:61:68: error: expected ‘{’ before ‘)’ token
       values_(new scoped_ptr<EnumValue>[descriptor_->value_count()]) {
                                                                    ^
enum.cc: In constructor ‘protobluff::Enum::Enum(const google::protobuf::EnumDescriptor*)’:
enum.cc:71:7: error: ‘values_’ was not declared in this scope
       values_[v].reset(sorted[v]);
       ^~~~~~~
enum.cc: In member function ‘void protobluff::Enum::GenerateValues(google::protobuf::io::Printer*) const’:
enum.cc:93:7: error: ‘values_’ was not declared in this scope
       values_[v]->GenerateValue(printer);
       ^~~~~~~
enum.cc: In member function ‘void protobluff::Enum::GenerateDescriptor(google::protobuf::io::Printer*) const’:
enum.cc:135:9: error: ‘values_’ was not declared in this scope
         values_[v]->GenerateDescriptor(printer);
         ^~~~~~~
Makefile:506: recipe for target 'protoc_gen_protobluff-enum.o' failed
make[3]: *** [protoc_gen_protobluff-enum.o] Error 1
make[3]: Leaving directory '/home/tam/protobuf-analysis/protobluff/src/generator'
Makefile:546: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/tam/protobuf-analysis/protobluff/src'
Makefile:500: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/tam/protobuf-analysis/protobluff'
Makefile:411: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by squidfunk** [comment]
Can you give some details on the versions you were using?

**Comment by ghost** [comment]
I clone the source from https://github.com/protocolbuffers/protobuf
commit 436139803ffbe0ca3dc0e563b63f29b2fd729d4f (HEAD -> master, origin/master, origin/HEAD)
Author: dyyap <35153938+dyyap@users.noreply.github.com>
Date:   Thu Nov 15 18:47:08 2018 -0800

    Updated README.md (#5366)
    
    * Update README.md

g++ (Ubuntu 7.2.0-8ubuntu3.2) 7.2.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Ubuntu 16.04

**Comment by squidfunk** [comment]
Which version of the `protobuf` library are you using? I mean the original Google Protocol Buffers C++ library which is necessary to compile the generator.

EDIT: ok, latest, so 3.6.1? Does it work with 3.6.0?

**Comment by squidfunk** [comment]
This could be related:

https://github.com/protocolbuffers/protobuf/blob/f22be4ddb0c8b8f81f84d106c74a812ee87f4c6b/CHANGES.txt#L20-L21

It seems that in order to be compatible with 3.6.x we need to adjust some types. Unfortunately my time is very limited at the moment, so I would suggest falling back to protobuf-3.5.1 when building the generator. I'm also happy to merge PRs.

**Comment by squidfunk** [comment]
Fixed in master by #4 for protobuf-3.6. Still errors for protobuf-3.7, waiting until we resolved them for a new release.

**Comment by squidfunk** [comment]
Fixed by a9cc5c1, released as part of 1.1.0.
